spring.application.name=invenatario
#datos para el acceso a la base de datos
url=jdbc:postgresql://localhost:5432/DB_multiservicio_rafael_c
user=user_rafael
password=Rafael2026@

#Este parte es las credenciales para enviar coreos electronicos
brevo.smtp.host=smtp-relay.brevo.com
brevo.smtp.port=587
brevo.smtp.user=ad5acd001@smtp-brevo.com
brevo.smtp.password=bAtnHhz8ZmSExJfY
brevo.smtp.from=tu_correo_verificado@tudominio.com
resend.api.key=re_DKif5vd6_4V5xsGFngSkgFJVd6Nu8HXLA