spring.application.name=invenatario
#datos para el acceso a la base de datos
url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
user=postgres.tqkqfvytchgkutvkehyi
password=MultiservicioRafael

#Este parte es las credenciales para enviar coreos electronicos
brevo.smtp.host=smtp-relay.brevo.com
brevo.smtp.port=2525
brevo.smtp.user=ad5acd001@smtp-brevo.com
brevo.smtp.password=xsmtpsib-cd9119d0ec2954dceedd71fec5494f918ad3962e135e23688b06403e070b0299-ZhbfuHrydRQpsGpH
brevo.smtp.from=rodriguezpenajosemanuel62@gmail.com

#clave Tocken de dni
apisperu.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJvZHJpZ3VlenBlbmFqb3NlbWFudWVsNjJAZ21haWwuY29tIn0.Lh9E8vEWog_SGGSq_UeGncbrG9VLEslXXi8cOOxbz_E
#clave tocken de ruc
apisperu.ruc.api.key=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InJvZHJpZ3VlenBlbmFqb3NlbWFudWVsNjJAZ21haWwuY29tIn0.Lh9E8vEWog_SGGSq_UeGncbrG9VLEslXXi8cOOxbz_E